name: gotest
on: [push, workflow_dispatch]
jobs:
  testgo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - name: Run tests
        run: go test -v .
        working-directory: ./godeploy
